export const products = [
    {   
        title:"torta de crema",
        price:1700,
        image:'image_1.jpg',
        category:"dulce",
        stock:8,
        id:1,
    },
    {
        title:"torta con frutillas",
        price:1800,
        image:'image_2.jpg',
        category:"dulce",
        stock:8,
        id:2,
    },
    {
        title:"mousse de chocolate",
        price:2000,
        image:'image_3.jpg',
        category:"dulce",
        stock:8,
        id:3,
    },
    {
        title:"torta de letra a",
        price:2000,
        image:'image_4.jpg',
        category:"salada",
        stock:8,
        id:4,
    },
    {
        title:"torta salada",
        price:2100,
        image:'image_5.jpg',
        category:"salada",
        stock:8,
        id:5,
    },
    {
        title:"torta con flores",
        price:2300,
        image:'image_6.jpg',
        category:"salada",
        stock:6,
        id:6,
    },
    {
        title:"torta con frutos rojos",
        price:1900,
        image:'image_7.jpg',
        category:"dulce",
        stock:6,
        id:7,
    },
    {
        title:"torta con letra r",
        price:2000,
        image:'image_8.jpg',
        category:"salada",
        stock:6,
        id:8,
    },
    {
        title:"torta con letra m",
        price:2000,
        image:'image_9.jpg',
        category:"salada",
        stock:6,
        id:9,
    },
    {
        title:"torta rectangular",
        price:1700,
        image:'image_10.jpg',
        category:"salada",
        stock:6,
        id:10,
    },
]
export default products

